#############################################################################
#
# Project Makefile
#
# (c) Wouter van Ooijen (www.voti.nl) 2016
#
# This file is in the public domain.
# 
#############################################################################

# source files in this project (main.cpp is automatically assumed)
SOURCES := ../ServoControllerDriver.cpp

# header files in this project
HEADERS := ../ServoControllerDriver.h 

# other places to look for files for this project
SEARCH  := PCA9685

# set RELATIVE to the next higher directory 
# and defer to the appropriate Makefile.* there
RELATIVE := $(HOME)/v1oopc-examples
include $(RELATIVE)/Makefile.due